stages:
  load_data:
    cmd: python src/data/load_data.py
    deps:
      - src/data/load_data.py
    outs:
      - data/raw  

  preprocess:
    cmd: python src/data/pre_process.py
    deps:
      - src/data/pre_process.py
      - data/raw
    outs:
      - data/silver  

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/silver
      - src/model.py
    outs:
      - paligemma_vqav2
